In [712]:
import numpy as np

In [713]:
with open('day5.txt') as f:
    lines = [line for line in f]   

In [715]:
seed_nums = lines[0].split(":")[1].split(" ")
seed_nums = [int(i) for i in seed_nums if i != '']
seed_nums

[3139431799,
 50198205,
 3647185634,
 110151761,
 2478641666,
 139825503,
 498892555,
 8913570,
 961540761,
 489996751,
 568452082,
 100080382,
 907727477,
 42158689,
 1617552130,
 312026427,
 342640189,
 97088268,
 2049289560,
 336766062]

In [716]:
# Get indices of where mapping starts in lines
map_indices = []
for i in range(len(lines)):
    split_by_colon = lines[i].split(":")
    if len(split_by_colon) !=1:
        map_indices.append(i)


# Get indices of start and finish places where instructions are for each mapping
map_index_values = []
for i in np.arange(1,len(map_indices)):
    if i!=len(map_indices)-1:
        map_index_values.append(np.arange(map_indices[i]+1,map_indices[i+1]))
    else:
        map_index_values.append(np.arange(map_indices[i]+1,len(lines)))
map_index_values
    
    

[array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43]),
 array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 64, 65, 66, 67, 68, 69, 70]),
 array([ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114]),
 array([116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128,
        129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141,
        142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163]),
 array([165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
        178, 179, 180, 181]),
 array([183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193,

In [717]:
lines

['seeds: 3139431799 50198205 3647185634 110151761 2478641666 139825503 498892555 8913570 961540761 489996751 568452082 100080382 907727477 42158689 1617552130 312026427 342640189 97088268 2049289560 336766062\n',
 '\n',
 'seed-to-soil map:\n',
 '1615836342 1401909974 23067952\n',
 '785532007 269485885 88937774\n',
 '3019002892 2773729385 10470414\n',
 '4202163101 2747292152 26437233\n',
 '3183210415 4217634159 77333137\n',
 '2847460091 3211730218 136699600\n',
 '2455891790 3791729773 70553041\n',
 '3260543552 2581343101 165949051\n',
 '3840286095 2849853212 361877006\n',
 '4228600334 2361239030 66366962\n',
 '1594559581 1077839137 21276761\n',
 '380069408 165017790 44262617\n',
 '3598718222 1894384162 241567873\n',
 '0 1424977926 190757551\n',
 '1894384162 2810496375 39356837\n',
 '424332025 606264721 196539291\n',
 '3521487829 2221977524 77230393\n',
 '742681934 69797365 36566707\n',
 '1638904294 1615735477 139190145\n',
 '1335949488 0 69797365\n',
 '779248641 802804012 6283366\n',
 '

In [718]:
mapping_instructions = {1:[],2:[],3:[],4:[],5:[],6:[],7:[]}
for i in range(len(map_index_values)):
    for index in map_index_values[i]:
        split_up = lines[index].split(' ')
        if len(split_up)!=1:
            data = [int(i) for i in split_up if i!= '']
            start_range = (data[1],data[1]+data[2]-1)
            destination_range = (data[0],data[0]+data[2]-1)
            mapping_instructions[i+1].append((start_range,destination_range))
mapping_instructions

{1: [((1401909974, 1424977925), (1615836342, 1638904293)),
  ((269485885, 358423658), (785532007, 874469780)),
  ((2773729385, 2784199798), (3019002892, 3029473305)),
  ((2747292152, 2773729384), (4202163101, 4228600333)),
  ((4217634159, 4294967295), (3183210415, 3260543551)),
  ((3211730218, 3348429817), (2847460091, 2984159690)),
  ((3791729773, 3862282813), (2455891790, 2526444830)),
  ((2581343101, 2747292151), (3260543552, 3426492602)),
  ((2849853212, 3211730217), (3840286095, 4202163100)),
  ((2361239030, 2427605991), (4228600334, 4294967295)),
  ((1077839137, 1099115897), (1594559581, 1615836341)),
  ((165017790, 209280406), (380069408, 424332024)),
  ((1894384162, 2135952034), (3598718222, 3840286094)),
  ((1424977926, 1615735476), (0, 190757550)),
  ((2810496375, 2849853211), (1894384162, 1933740998)),
  ((606264721, 802804011), (424332025, 620871315)),
  ((2221977524, 2299207916), (3521487829, 3598718221)),
  ((69797365, 106364071), (742681934, 779248640)),
  ((1615735477, 

In [719]:
def get_mapping(initial,mapping_list):
    x = initial
    for maps in mapping_list:
        if x>=maps[0][0] and x<=maps[0][1]:
            return maps[1][0]+x-maps[0][0]
    
    return initial
        

final_answers=[]
for i in range(len(seed_nums)):
    s = seed_nums[i]
    for j in np.arange(1,8):
        s=get_mapping(s,mapping_instructions[j])
    final_answers.append(s)

In [720]:
min(final_answers)

462648396

## Part 2
- Wow, this was insanely difficult. But I did it.
- It would be way too computationally intense to pipe through all the seeds to find out their locations and brute force it
- Instead you have to basically work backwards.
- I start from all the ranges of possible locations (i.e. the ranges of the final map)
- from there, you look at the domains of the final map which correpond to this
- I built an "overlap" function, so I find the overlap of the domain of the final map with the range of the penultimate map
- This means I don't need to consider EVERY SINGLE seed going through the final map, only the smallest value of each interval in this list of overlaps.
- I then use the mapping to pipe this list of ranges BACKWARDS through the 5th map to get a new set of domains for the fifth map
- I then iteratively continue this through all of the maps: first overlapping range and domains when they are next to eachtoher, then mapping backwards through
- Once I finally end up with a list of ranges of seed numbers, I only have to pipe through the lowest values in each range.
- Basically the final result I have is that I've combined all the maps into one large map, meaning I need only consider the lowest values of each pair

In [721]:
seed_ranges = []

In [740]:
# Parse the seed ranges that we have as input
for i in range(int(len(seed_nums)/2)):
    seed_ranges.append((seed_nums[2*i],seed_nums[2*i]+seed_nums[2*i+1]))
seed_ranges
    

[(3139431799, 3189630004),
 (3647185634, 3757337395),
 (2478641666, 2618467169),
 (498892555, 507806125),
 (961540761, 1451537512),
 (568452082, 668532464),
 (907727477, 949886166),
 (1617552130, 1929578557),
 (342640189, 439728457),
 (2049289560, 2386055622),
 (3139431799, 3189630004),
 (3647185634, 3757337395),
 (2478641666, 2618467169),
 (498892555, 507806125),
 (961540761, 1451537512),
 (568452082, 668532464),
 (907727477, 949886166),
 (1617552130, 1929578557),
 (342640189, 439728457),
 (2049289560, 2386055622)]

In [723]:
class Pipeline:
    """
    Class representing one of the maps
    list_of_maps is a list of tuples representing domain:range 
    domain/ range are self-explanatory, but they are padded out with (0,X) and (Y,10^25) as boundaries
    backwards = True/False is a parameter that lets me use this pipeline to either map forwards or backwards
    .pipe is a method which takes in a number and gives the output
    """

    def __init__(self,list_of_maps,backwards):
        
        self.list_of_maps = sorted(list_of_maps, key=lambda x: x[0])

        self.domain = [i[0] for i in list_of_maps]
        self.domain.sort()
        if 0 not in [i[0] for i in self.domain]:
            min_val = min([i[0] for i in self.domain])
            self.domain = [(0,min_val-1)]+self.domain
            
        max_val = max([i[1] for i in self.domain])
        self.domain = self.domain + [(max_val+1,10**25)]
        
        
        
        self.range = [i[1] for i in list_of_maps]

        if 0 not in [i[0] for i in self.range]:
            min_val = min([i[0] for i in self.range])
            self.range = [(0,min_val-1)]+self.range
            
        max_val = max([i[1] for i in self.range])
        self.range = self.range + [(max_val+1,10**25)]
        
        
        
        if backwards:
            self.list_of_maps = [(i[1],i[0]) for i in self.list_of_maps]
            d = self.domain.copy()
            r = self.range.copy()
            self.domain = r
            self.range = d
        
        
    def pipe(self,input_val):
        for j in self.list_of_maps:
            if input_val >=j[0][0] and input_val<=j[0][1]:
                return j[1][0]+(input_val-j[0][0])
        
        return input_val
        

        

In [724]:
# Find the list of overlaps of two intervals (x,y) and (a,b)
def find_overlap(interval1, interval2):
    start1, end1 = interval1
    start2, end2 = interval2

    # Check for no overlap
    if end1 < start2 or end2 < start1:
        return None

    # Calculate overlap
    overlap_start = max(start1, start2)
    overlap_end = min(end1, end2)

    return overlap_start, overlap_end
        

In [725]:
# Find overlaps of list of ranges and domains
def get_new_range_based_on_overlap(range_input,target_domain):
    new_range_1 = []
    for r in range_input:
        for d in target_domain:
            overlap = find_overlap(r,d)
            if overlap != None:
                new_range_1.append(overlap)
    return(new_range_1)



In [729]:
def pipe_backwards(range_pair,model):
    return(model.pipe(range_pair[0]),model.pipe(range_pair[1]))

In [730]:
# This merges the pipelines!
pipes = [Pipeline(mapping_instructions[i],False) for i in np.arange(1,8)]
backward_pipes = [Pipeline(mapping_instructions[i],True) for i in np.arange(1,8)]

#This is the main algo, we start with the domain of the final map
current_domain = pipes[6].domain
#Then we final overlaps with the range of the map before it
next_step=get_new_range_based_on_overlap(current_domain,pipes[5].range)
#Then we pipe these overlaps back through the penultimate map to land of domains 
next_step = [pipe_backwards(i,backward_pipes[5]) for i in next_step]
# Then we overlap these domains with the range of the map before this one...etc.
next_step=get_new_range_based_on_overlap(next_step,pipes[4].range)
next_step = [pipe_backwards(i,backward_pipes[4]) for i in next_step]
next_step=get_new_range_based_on_overlap(next_step,pipes[3].range)
next_step = [pipe_backwards(i,backward_pipes[3]) for i in next_step]
next_step=get_new_range_based_on_overlap(next_step,pipes[2].range)
next_step = [pipe_backwards(i,backward_pipes[2]) for i in next_step]
next_step=get_new_range_based_on_overlap(next_step,pipes[1].range)
next_step = [pipe_backwards(i,backward_pipes[1]) for i in next_step]
next_step=get_new_range_based_on_overlap(next_step,pipes[0].range)
next_step = [pipe_backwards(i,backward_pipes[0]) for i in next_step]
next_step

[(3591409454, 3591970986),
 (3265008430, 3293501800),
 (3791729773, 3862282813),
 (2135952035, 2169313794),
 (4008405072, 4008940963),
 (2169313795, 2208151884),
 (2895238498, 2922930398),
 (3211730218, 3216474670),
 (4210808215, 4217634158),
 (3591970987, 3606925785),
 (380456432, 390791998),
 (1142644585, 1186340058),
 (265886324, 269485884),
 (173116881, 184490861),
 (1327596510, 1329184701),
 (63195228, 69797364),
 (1213097246, 1228757298),
 (165017790, 173116880),
 (162965392, 165017789),
 (2604211115, 2616633803),
 (4289491596, 4294967295),
 (2581343101, 2604211114),
 (3018496181, 3022773996),
 (3249339581, 3265008429),
 (3606925786, 3608249263),
 (2552657789, 2563377601),
 (2760100896, 2771403180),
 (3216474671, 3225535083),
 (688694616, 696989099),
 (244616075, 265886323),
 (143867672, 162965391),
 (1016422183, 1076471518),
 (1302460638, 1327596509),
 (2563377602, 2570301101),
 (3510945407, 3570553821),
 (4278967032, 4289491595),
 (646330308, 658750825),
 (4277458121, 427896703

In [731]:
pipeline_of_pipes = [Pipeline(mapping_instructions[i],False) for i in np.arange(1,8)]

In [732]:
# Combine all pipes to get one final number
def pipe_through_whole_thing(x):
    output = x
    for j in np.arange(0,7):        
        output = pipeline_of_pipes[j].pipe(output)
    return(output)

In [733]:
# Output of algo above is a list of domains
# Need to overlap this with the input seed ranges, but being careful to do a more sophisticated overlap 
# because we have prescribed list of input seeds, it's not just the generic overlap!
def find_overlap_with_seeds(interval_a, interval_b):

    start_a, end_a = interval_a
    start_b, end_b = interval_b

    # Check for no overlap
    if end_a < start_b or end_b < start_a:
        return None

    # Calculate overlap
    overlap_start = max(start_a, start_b)
    overlap_end = min(end_a, end_b)

    # Ensure overlap elements are in interval_a
    overlap_start = max(overlap_start, start_a)
    overlap_end = min(overlap_end, end_a)

    # Check if there is still an overlap after adjusting for interval_a
    if overlap_end < overlap_start:
        return None

    return overlap_start, overlap_end



In [734]:
seed_ranges

[(3139431799, 3189630004),
 (3647185634, 3757337395),
 (2478641666, 2618467169),
 (498892555, 507806125),
 (961540761, 1451537512),
 (568452082, 668532464),
 (907727477, 949886166),
 (1617552130, 1929578557),
 (342640189, 439728457),
 (2049289560, 2386055622)]

In [738]:
# Compute final seed overlap
final_seeds = []
for s in seed_ranges:
    for n in next_step:
        output = find_overlap_with_seeds(s,n)
        if output!=None:
            final_seeds.append(output)


In [736]:
# Final the seed values at the beginning of each of the ranges
min_vals = [i[0] for i in final_seeds]
# Pipe these seed values through the pipeline.
results = [pipe_through_whole_thing(i) for i in min_vals]

In [737]:
min(results)

2520479